# Generated by Django 5.2 on 2025-04-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menuitem_image_restaurant_image_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='main.restaurant'),
        ),
    ]
